# Generated by Django 3.0 on 2022-01-21 22:08

from django.db import migrations


def copy_profile_table(apps, schema_editor):
    OldProfile = apps.get_model("oc_lettings_site", "Profile")
    Profile = apps.get_model("profiles", "Profile")
    User = apps.get_model("auth", "User")

    for old_profile in OldProfile.objects.all():
        Profile.objects.create(**{
            "favorite_city": getattr(old_profile, "favorite_city"),
            "user": User.objects.get(username=old_profile.user.username)
        })


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_profile_table),
    ]
