# Generated by Django 3.0 on 2022-01-21 22:08

from django.db import migrations


ADDRESS_FIELDS = (
    "number",
    "street",
    "city",
    "state",
    "zip_code",
    "country_iso_code"
)


def copy_address_table(apps, schema_editor):
    OldAddress = apps.get_model("oc_lettings_site", "Address")
    Address = apps.get_model("lettings", "Address")

    for old_address in OldAddress.objects.all():
        Address.objects.create(
            **{field: getattr(old_address, field) for field in ADDRESS_FIELDS}
        )


def copy_letting_table(apps, schema_editor):
    OldLetting = apps.get_model("oc_lettings_site", "Letting")
    Letting = apps.get_model("lettings", "Letting")
    Address = apps.get_model("lettings", "Address")

    for old_letting in OldLetting.objects.all():
        Letting.objects.create(**{
            "title": getattr(old_letting, "title"),
            "address": Address.objects.get(
                **{field: getattr(old_letting.address, field) for field in ADDRESS_FIELDS}
            )
        })


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_address_table),
        migrations.RunPython(copy_letting_table),
    ]
