version: 2.1


orbs:
  python: circleci/python@1.5
  docker: circleci/docker@2.0.1


workflows:
  version: 2
  test-build-publish-deploy:
    jobs:
      - test-code
      - docker/publish:
          image: timgelibert/oc-lettings
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_TOKEN
          requires:
            - test-code
          filters:
            branches:
              only: master
      - push-docker-image-to-heroku:
          requires:
            - docker/publish
          filters:
            branches:
              only: master


jobs:
  test-code:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Pytest
          command: pytest
      - run:
          name: Flake8
          command: flake8
  push-docker-image-to-heroku:
    machine: true
    steps:
      - run:
          name: Pass heroku step
          command: echo "Not pushing docker image to Heroku from CI/CD yet."