version: 2.1


orbs:
  python: circleci/python@1.5
  docker: circleci/docker@2.0.1
  heroku: circleci/heroku@1.2.6


workflows:
  version: 2
  check-build-and-push-app:
    jobs:
      - build-and-test-python
      - build-push-docker-and-deploy-to-heroku:
          requires:
            - build-and-test-python
          filters:
            branches:
              only: master


jobs:
  build-and-test-python:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Pytest
          command: pytest
      - run:
          name: Flake8
          command: flake8
  build-push-docker-and-deploy-to-heroku:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: timgelibert/oc-lettings-13
      - docker/push:
          image: timgelibert/oc-lettings-13
      - heroku/install
      - run:
          name: Set heroku git:remote
          command: heroku git:remote -a oc-lettings-13
      - heroku/push-docker-image:
          process-types: web
      - run:
          name: Release
          command: heroku container:release web --app oc-lettings-13
      - run:
          name: Define SECRET_KEY
          command: heroku config:set SECRET_KEY=$SECRET_KEY
      - run:
          name: Define SENTRY_CREDENTIALS
          command: heroku config:set SENTRY_CREDENTIALS=$SENTRY_CREDENTIALS
      - run:
          name: Define DEBUG key
          command: heroku config:set DEBUG=$DEBUG