version: 2.1


orbs:
  python: circleci/python@1.5
  docker: circleci/docker@2.0.1
  heroku: circleci/heroku@1.2.6


workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test-code
      - build-and-push-docker-image:
          requires:
            - test-code
          filters:
            branches:
              only: master
      - push-docker-image-to-heroku:
          requires:
            - build-and-push-docker-image
          filters:
            branches:
              only: master


jobs:
  test-code:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Pytest
          command: pytest
      - run:
          name: Flake8
          command: flake8
  build-and-push-docker-image:
    machine: true
    steps:
      - run:
          name: Pass docker step
          command: echo "Not building docker image from CI/CD yet."
  push-docker-image-to-heroku:
    machine: true
    steps:
      - run:
          name: Pass heroku step
          command: echo "Not pushing docker image to Heroku from CI/CD yet."